# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/src/liteDRAM.xdc

# XDC: imports/src/rvfpga.xdc

# Block Designs: bd/BD/BD.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD || ORIG_REF_NAME==BD} -quiet] -quiet

# IP: bd/BD/ip/BD_swerv_wrapper_verilog_0_0/BD_swerv_wrapper_verilog_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_swerv_wrapper_verilog_0_0 || ORIG_REF_NAME==BD_swerv_wrapper_verilog_0_0} -quiet] -quiet

# IP: bd/BD/ip/BD_intcon_wrapper_bd_0_0/BD_intcon_wrapper_bd_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_intcon_wrapper_bd_0_0 || ORIG_REF_NAME==BD_intcon_wrapper_bd_0_0} -quiet] -quiet

# IP: bd/BD/ip/BD_gpio_wrapper_0_0/BD_gpio_wrapper_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_gpio_wrapper_0_0 || ORIG_REF_NAME==BD_gpio_wrapper_0_0} -quiet] -quiet

# IP: bd/BD/ip/BD_syscon_wrapper_0_0/BD_syscon_wrapper_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_syscon_wrapper_0_0 || ORIG_REF_NAME==BD_syscon_wrapper_0_0} -quiet] -quiet

# IP: bd/BD/ip/BD_bootrom_wrapper_0_0/BD_bootrom_wrapper_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_bootrom_wrapper_0_0 || ORIG_REF_NAME==BD_bootrom_wrapper_0_0} -quiet] -quiet

# IP: bd/BD/ip/BD_bidirec_0_0/BD_bidirec_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_bidirec_0_0 || ORIG_REF_NAME==BD_bidirec_0_0} -quiet] -quiet

# IP: bd/BD/ip/BD_bidirec_0_1/BD_bidirec_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_bidirec_0_1 || ORIG_REF_NAME==BD_bidirec_0_1} -quiet] -quiet

# IP: bd/BD/ip/BD_bidirec_0_2/BD_bidirec_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_bidirec_0_2 || ORIG_REF_NAME==BD_bidirec_0_2} -quiet] -quiet

# IP: bd/BD/ip/BD_bidirec_1_0/BD_bidirec_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_bidirec_1_0 || ORIG_REF_NAME==BD_bidirec_1_0} -quiet] -quiet

# IP: bd/BD/ip/BD_bidirec_0_3/BD_bidirec_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_bidirec_0_3 || ORIG_REF_NAME==BD_bidirec_0_3} -quiet] -quiet

# IP: bd/BD/ip/BD_bidirec_1_1/BD_bidirec_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_bidirec_1_1 || ORIG_REF_NAME==BD_bidirec_1_1} -quiet] -quiet

# IP: bd/BD/ip/BD_bidirec_2_0/BD_bidirec_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_bidirec_2_0 || ORIG_REF_NAME==BD_bidirec_2_0} -quiet] -quiet

# IP: bd/BD/ip/BD_bidirec_3_0/BD_bidirec_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_bidirec_3_0 || ORIG_REF_NAME==BD_bidirec_3_0} -quiet] -quiet

# IP: bd/BD/ip/BD_bidirec_0_4/BD_bidirec_0_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_bidirec_0_4 || ORIG_REF_NAME==BD_bidirec_0_4} -quiet] -quiet

# IP: bd/BD/ip/BD_bidirec_1_2/BD_bidirec_1_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_bidirec_1_2 || ORIG_REF_NAME==BD_bidirec_1_2} -quiet] -quiet

# IP: bd/BD/ip/BD_bidirec_2_1/BD_bidirec_2_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_bidirec_2_1 || ORIG_REF_NAME==BD_bidirec_2_1} -quiet] -quiet

# IP: bd/BD/ip/BD_bidirec_3_1/BD_bidirec_3_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_bidirec_3_1 || ORIG_REF_NAME==BD_bidirec_3_1} -quiet] -quiet

# IP: bd/BD/ip/BD_bidirec_4_0/BD_bidirec_4_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_bidirec_4_0 || ORIG_REF_NAME==BD_bidirec_4_0} -quiet] -quiet

# IP: bd/BD/ip/BD_bidirec_5_0/BD_bidirec_5_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_bidirec_5_0 || ORIG_REF_NAME==BD_bidirec_5_0} -quiet] -quiet

# IP: bd/BD/ip/BD_bidirec_6_0/BD_bidirec_6_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_bidirec_6_0 || ORIG_REF_NAME==BD_bidirec_6_0} -quiet] -quiet

# IP: bd/BD/ip/BD_bidirec_7_0/BD_bidirec_7_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_bidirec_7_0 || ORIG_REF_NAME==BD_bidirec_7_0} -quiet] -quiet

# IP: bd/BD/ip/BD_bidirec_0_5/BD_bidirec_0_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_bidirec_0_5 || ORIG_REF_NAME==BD_bidirec_0_5} -quiet] -quiet

# IP: bd/BD/ip/BD_bidirec_1_3/BD_bidirec_1_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_bidirec_1_3 || ORIG_REF_NAME==BD_bidirec_1_3} -quiet] -quiet

# IP: bd/BD/ip/BD_bidirec_10_0/BD_bidirec_10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_bidirec_10_0 || ORIG_REF_NAME==BD_bidirec_10_0} -quiet] -quiet

# IP: bd/BD/ip/BD_bidirec_11_0/BD_bidirec_11_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_bidirec_11_0 || ORIG_REF_NAME==BD_bidirec_11_0} -quiet] -quiet

# IP: bd/BD/ip/BD_bidirec_12_0/BD_bidirec_12_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_bidirec_12_0 || ORIG_REF_NAME==BD_bidirec_12_0} -quiet] -quiet

# IP: bd/BD/ip/BD_bidirec_13_0/BD_bidirec_13_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_bidirec_13_0 || ORIG_REF_NAME==BD_bidirec_13_0} -quiet] -quiet

# IP: bd/BD/ip/BD_bidirec_14_0/BD_bidirec_14_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_bidirec_14_0 || ORIG_REF_NAME==BD_bidirec_14_0} -quiet] -quiet

# IP: bd/BD/ip/BD_bidirec_15_0/BD_bidirec_15_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_bidirec_15_0 || ORIG_REF_NAME==BD_bidirec_15_0} -quiet] -quiet

# IP: bd/BD/ip/BD_bidirec_2_2/BD_bidirec_2_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_bidirec_2_2 || ORIG_REF_NAME==BD_bidirec_2_2} -quiet] -quiet

# IP: bd/BD/ip/BD_bidirec_3_2/BD_bidirec_3_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_bidirec_3_2 || ORIG_REF_NAME==BD_bidirec_3_2} -quiet] -quiet

# IP: bd/BD/ip/BD_bidirec_4_1/BD_bidirec_4_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_bidirec_4_1 || ORIG_REF_NAME==BD_bidirec_4_1} -quiet] -quiet

# IP: bd/BD/ip/BD_bidirec_5_1/BD_bidirec_5_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_bidirec_5_1 || ORIG_REF_NAME==BD_bidirec_5_1} -quiet] -quiet

# IP: bd/BD/ip/BD_bidirec_6_1/BD_bidirec_6_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_bidirec_6_1 || ORIG_REF_NAME==BD_bidirec_6_1} -quiet] -quiet

# IP: bd/BD/ip/BD_bidirec_7_1/BD_bidirec_7_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_bidirec_7_1 || ORIG_REF_NAME==BD_bidirec_7_1} -quiet] -quiet

# IP: bd/BD/ip/BD_bidirec_8_0/BD_bidirec_8_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_bidirec_8_0 || ORIG_REF_NAME==BD_bidirec_8_0} -quiet] -quiet

# IP: bd/BD/ip/BD_bidirec_9_0/BD_bidirec_9_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==BD_bidirec_9_0 || ORIG_REF_NAME==BD_bidirec_9_0} -quiet] -quiet

# XDC: bd/BD/BD_ooc.xdc
